# Generated by Django 5.1 on 2024-09-14 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_post', '0001_initial'),
        ('api_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='api_user.user'),
        ),
    ]
